importações

In [21]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pandas as pd

leitura do csv

In [22]:
df = pd.read_csv('./bi/dataframe_cotacao.tsv', sep='\t')

variaveis de leitura do tsv

In [23]:
# variavel para guardar a liquidez
liquidez_valor = df['Liquidez Diária']
# variavel para guardar os valores das cotas
valor_cota = df['Preço Atual']

In [24]:
rotulo = df['Setor']

preparando o as listas dos graficos

In [25]:
lista_lq = [] #liquidez_diaria
lista_vc = [] #preço atual
for lq, vc in zip(liquidez_valor,valor_cota):
    try:
        lq = float(lq)
        vc = vc.split()
        vc = vc[-1]
        vc = vc.replace(',','.')
        vc = float(vc)
        lista_lq.append(lq)
        lista_vc.append(vc)
    except:
        pass

In [26]:
lista_lq = [] #liquidez_diaria
lista_vc = [] #preço atual
lista_rt = [] #rotulo
for lq, vc, rt in zip(liquidez_valor,valor_cota, rotulo):
    try:
        lq = float(lq)
        vc = vc.split()
        vc = vc[-1]
        vc = vc.replace(',','.')
        vc = float(vc)
        lista_lq.append(lq)
        lista_vc.append(vc)
        lista_rt.append(rt)
    except:
        pass

grafico de dispersão

In [27]:
grafico_s_rt = px.scatter(y=lista_lq, x=lista_vc)
grafico_s_rt.show()

In [28]:
grafico_c_rt = px.scatter(y=lista_lq, x=lista_vc, color=lista_rt)
grafico_c_rt.show()

Transformando em matriz

In [29]:
lista_cotacao = []
for x,y in zip(lista_lq, lista_vc):
    item = [x,y]
    lista_cotacao.append(item)

print(lista_cotacao)

[[2454.0, 2.38], [44041.0, 14.7], [2702.0, 6.29], [29.0, 842.0], [67.0, 9.4], [3.0, 93.0], [200.0, 165.0], [11.0, 84.96], [5.0, 351.0], [3597.0, 115.5], [1354.0, 4.49], [33.0, 33.85], [5.0, 112.0], [41.0, 784.0], [34.0, 62.01], [2823.0, 0.96], [98.0, 3.71], [22.0, 35.06], [408.0, 42.42], [5495.0, 910.0], [2130.0, 1.04], [1539.0, 81.89], [61.0, 94.0], [49.0, 240.99], [7.0, 86.48], [206.0, 12.78], [47.0, 7.1], [218.0, 70.25], [13485.0, 4.09], [1366.0, 79.6], [5157.0, 28.45], [148.0, 62.5], [109581.0, 8.06], [52.0, 98.84], [21378.0, 89.8], [9.0, 195.0], [23.0, 87.92], [2128.0, 97.0], [69685.0, 93.84], [35771.0, 97.12], [32195.0, 153.18], [3677.0, 13.99], [6629.0, 92.51], [567.0, 98.88], [15393.0, 99.13], [32541.0, 124.49], [61169.0, 9.4], [8879.0, 85.0], [107752.0, 7.73], [92795.0, 87.75], [709.0, 71.97], [480.0, 80.94], [365.0, 65.82], [3651.0, 101.87], [8659.0, 69.2], [919.0, 78.55], [36579.0, 103.7], [79.0, 109.5], [4545.0, 43.01], [18687.0, 80.0], [211.0, 87.58], [5147.0, 85.1], [1409

In [30]:
base_cotacoes = np.array(lista_cotacao)

treino

In [31]:
scaler_base = StandardScaler()
base_cotacoes = scaler_base.fit_transform(base_cotacoes)
base_cotacoes

array([[-2.70811973e-01, -8.69068912e-01],
       [ 3.91805095e-01, -7.57900752e-01],
       [-2.66860521e-01, -8.33787459e-01],
       [-3.09450163e-01,  6.70714944e+00],
       [-3.08844698e-01, -8.05724717e-01],
       [-3.09864428e-01, -5.13693488e-02],
       [-3.06725573e-01,  5.98314701e-01],
       [-3.09736962e-01, -1.23917401e-01],
       [-3.09832561e-01,  2.27666516e+00],
       [-2.52600241e-01,  1.51656917e-01],
       [-2.88338575e-01, -8.50029560e-01],
       [-3.09386430e-01, -5.85102842e-01],
       [-3.09832561e-01,  1.20075053e-01],
       [-3.09258964e-01,  6.18379285e+00],
       [-3.09370497e-01, -3.31004192e-01],
       [-2.64932595e-01, -8.81882125e-01],
       [-3.08350767e-01, -8.57067804e-01],
       [-3.09561696e-01, -5.74184541e-01],
       [-3.03411452e-01, -5.07772393e-01],
       [-2.22358887e-01,  7.32073993e+00],
       [-2.75974354e-01, -8.81160254e-01],
       [-2.85390919e-01, -1.51619207e-01],
       [-3.08940298e-01, -4.23459592e-02],
       [-3.

cluster

separando o numero de segmentos

In [32]:
n_cluster = df['Setor']
n_cluster = set(n_cluster)
n_cluster = len(n_cluster)
n_cluster

10

In [33]:
k_means_cotacao = KMeans(n_clusters=n_cluster)
k_means_cotacao.fit(base_cotacoes)

KMeans(n_clusters=10)

localizando os pontos de referencia

In [34]:
centroides = k_means_cotacao.cluster_centers_
centroides

array([[-0.25663038, -0.1290531 ],
       [-0.29132447,  6.37508871],
       [ 1.2676789 , -0.81024462],
       [13.22465522, -0.79814507],
       [ 5.01186504, -0.79963393],
       [-0.24791211, -0.68531289],
       [-0.30307685,  2.82939289],
       [ 0.51645906, -0.1301285 ],
       [-0.29026422,  1.24021285],
       [-0.07119777,  0.15951941]])

vizualizando centros em 2D matematicamente pelo reverse scaler

In [35]:
# scaler_base.inverse_transform(k_means_cotacao.cluster_centers_)

add rotulos

In [36]:
rotulos = k_means_cotacao.labels_
rotulos

array([5, 7, 5, 1, 5, 0, 9, 0, 6, 9, 5, 5, 9, 1, 0, 5, 5, 5, 5, 1, 5, 0,
       0, 8, 0, 5, 5, 0, 5, 0, 5, 0, 2, 0, 9, 8, 0, 0, 7, 7, 9, 5, 0, 0,
       9, 9, 2, 0, 2, 7, 0, 0, 0, 0, 0, 0, 7, 0, 5, 0, 0, 0, 0, 0, 0, 2,
       5, 9, 9, 9, 9, 0, 6, 0, 5, 0, 0, 0, 5, 7, 7, 9, 0, 7, 2, 0, 0, 0,
       9, 0, 0, 5, 0, 2, 7, 5, 9, 0, 9, 0, 0, 0, 9, 0, 5, 0, 0, 0, 0, 0,
       9, 9, 0, 0, 2, 0, 8, 9, 9, 9, 3, 0, 9, 5, 7, 0, 5, 0, 9, 9, 0, 0,
       9, 0, 9, 0, 0, 1, 9, 0, 9, 0, 0, 0, 9, 0, 0, 5, 0, 8, 0, 0, 0, 4,
       2, 9, 0, 7, 9, 0, 0, 7, 0, 9, 8, 8, 5, 5, 8, 9, 0, 0, 0, 0, 0, 5,
       0, 9, 0, 0, 0, 9, 5, 0, 5, 2, 0, 0, 7, 0, 0, 2, 7, 0, 9, 0, 7, 9,
       0, 0, 9, 7, 5, 0, 0, 0, 0, 0, 7, 0, 0, 7, 0, 9, 9, 1, 9, 0, 0, 0,
       9, 0, 0, 9, 0, 0, 7, 5, 0, 4, 7, 7, 2, 7, 7, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 9, 9, 9, 9, 0, 0, 0, 0, 9, 0, 7, 0, 9, 0, 0, 0, 9, 9, 9,
       5, 0, 5, 0])

grafico do cluster

In [37]:
grafico_cluster = px.scatter(y=base_cotacoes[:,0], x=base_cotacoes[:,1], color=rotulos)
grafico_centroid = px.scatter(y=centroides[:,0], x=centroides[:,1], size=[1,2,3,4,5,6,7,8,9,10])
grafico_geral = go.Figure(data=grafico_cluster.data + grafico_centroid.data)
grafico_geral.show()

In [38]:
n_cluster = df['Setor']
n_cluster = set(n_cluster)
nome_cluster = n_cluster
for id, x in enumerate(nome_cluster):
    id_n = id+1
    print(id_n,x)

1 nan
2 Híbrido
3 Outros
4 Lajes Corporativas
5 Hospital
6 Shoppings
7 Títulos e Val. Mob.
8 Residencial
9 Hotel
10 Logística


o X referece ao numero de ações em circulação
o Y referece ao valor da ação

In [39]:
grafico_c_rt = px.scatter(y=lista_lq, x=lista_vc, color=lista_rt)
grafico_c_rt.show()