importações

In [24]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pandas as pd
import datetime

leitura do csv

In [25]:
data = datetime.date.today()

In [26]:
df = pd.read_csv(f'../bi/{data}_dataframe_cotacao.tsv', sep='\t')
df

Unnamed: 0 Codigo_do_fundo                Setor Preco_Atual  \
0             0          FIVN11            Shoppings     R$ 3,23   
1             1          BZLI11  Títulos e Val. Mob.    R$ 17,00   
2             2          XTED11   Lajes Corporativas     R$ 7,25   
3             3          ALMI11   Lajes Corporativas   R$ 910,00   
4             4          PABY11              Híbrido     R$ 7,30   
..          ...             ...                  ...         ...   
301         301          MFAI11              Híbrido    R$ 66,48   
302         302          BBFO11  Títulos e Val. Mob.    R$ 77,11   
303         303          MFII11              Híbrido    R$ 96,49   
304         304          RZAG11  Títulos e Val. Mob.    R$ 10,07   
305         305          XPCA11  Títulos e Val. Mob.    R$ 10,25   

     Liquidez_Diaria Dividendo DividendYield DY_(3M)Acumulado  \
0             1850.0   R$ 0,00         0,00%            0,00%   
1                1.0   R$ 0,00         0,00%            0,00%   
2             1088.0   R$ 0,00         0,00%            0,00%   
3               18.0   R$ 0,00         0,00%            0,00%   
4                4.0   R$ 0,00         0,00%            0,00%   
..               ...       ...           ...              ...   
301            554.0   R$ 0,70         1,05%            2,91%   
302           2264.0   R$ 0,70         0,91%            3,14%   
303           4741.0   R$ 1,09         1,13%            3,43%   
304         271899.0   R$ 0,14         1,39%            4,07%   
305         151848.0   R$ 0,14         1,37%            4,00%   

    DY_(6M)Acumulado DY_(12M)Acumulado  ...     PatrimônioLíq.          VPA  \
0              0,00%             0,00%  ...   R$ 65.491.905,42      R$ 6,96   
1              0,00%             0,00%  ...  R$ 440.205.505,76     R$ 10,78   
2              0,00%             0,00%  ...   R$ 27.085.416,91     R$ 13,78   
3              0,00%             0,00%  ...  R$ 250.158.727,48  R$ 2.250,09   
4              0,00%             0,00%  ...  R$ -10.950.151,50    R$ -14,44   
..               ...               ...  ...                ...          ...   
301            4,86%            12,33%  ...   R$ 24.142.001,77     R$ 78,06   
302            6,56%            12,33%  ...  R$ 349.116.913,80     R$ 87,19   
303            6,77%            13,46%  ...  R$ 416.574.943,40    R$ 100,45   
304            7,80%             0,00%  ...  R$ 289.264.320,71      R$ 9,53   
305            8,11%             0,00%  ...  R$ 168.095.144,07      R$ 9,50   

     P_VPA DYPatrimonial Variacao_Patrimonial Rentab._Patr.no_Periodo  \
0     46.0           NaN                  NaN                     NaN   
1    158.0           NaN                  NaN                     NaN   
2     53.0           NaN                  NaN                     NaN   
3     40.0           NaN                  NaN                     NaN   
4    -51.0           NaN                  NaN                     NaN   
..     ...           ...                  ...                     ...   
301   85.0         0,86%                6,46%                   7,37%   
302   88.0         0,87%                4,63%                   5,54%   
303   96.0         1,10%               -0,06%                   1,03%   
304  106.0         1,47%                0,05%                   1,52%   
305  108.0         1,47%                0,04%                   1,52%   

    Rentab._Patr.Acumulada Vacancia_Fisica VacanciaFinanceira  \
0                      NaN          56,00%                NaN   
1                      NaN             NaN                NaN   
2                      NaN           0,00%            100,00%   
3                      NaN          64,05%                NaN   
4                      NaN             NaN                NaN   
..                     ...             ...                ...   
301                  1,32%             NaN                NaN   
302                  8,43%             NaN                NaN

variaveis de leitura do tsv

In [27]:
# variavel para guardar a liquidez
liquidez_valor = df['Liquidez_Diaria']
# variavel para guardar os valores das cotas
valor_cota = df['Preco_Atual']

preparando o as listas dos graficos

In [28]:
lista_lq = [] #liquidez_diaria
lista_vc = [] #preço atual
for lq, vc in zip(liquidez_valor,valor_cota):
    try:
        vc = vc.split(' ')[-1]
        vc = vc.replace(',', '.')
        vc = float(vc)
        lista_lq.append(lq)
        lista_vc.append(vc)
    except:
        pass

grafico de dispersão

altura referece a liquidez diaria, x referece ao valor da cota

In [29]:
grafico_s_rt = px.scatter(y=lista_lq, x=lista_vc)
grafico_s_rt.show()

In [30]:
rotulo = df['Setor']

In [31]:
lista_lq = [] #liquidez_diaria
lista_vc = [] #preço atual
lista_rt = [] #rotulo
for lq, vc, rt in zip(liquidez_valor,valor_cota, rotulo):
    try:
        vc = vc.split(' ')[-1]
        vc = vc.replace(',', '.')
        vc = float(vc)
        lista_lq.append(lq)
        lista_vc.append(vc)
        lista_rt.append(rt)
    except:
        pass

In [32]:
grafico_c_rt = px.scatter(y=lista_lq, x=lista_vc, color=lista_rt)
grafico_c_rt.show()

Transformando em matriz

In [33]:
lista_cotacao = []
for x,y in zip(lista_lq, lista_vc):
    item = [x,y]
    lista_cotacao.append(item)
print(lista_cotacao)

[[1850.0, 3.23], [1.0, 17.0], [1088.0, 7.25], [18.0, 910.0], [4.0, 7.3], [3.0, 93.0], [200.0, 165.0], [42.0, 80.03], [1959.0, 116.69], [2642.0, 4.75], [38.0, 35.21], [626.0, 122.0], [4.0, 784.0], [3.0, 64.99], [0.0, 0.0], [1813.0, 0.99], [329.0, 3.5], [60.0, 36.71], [1260.0, 47.0], [8830.0, 923.0], [240.0, 950.0], [332.0, 1.03], [15.0, 83.0], [1.0, 87.9], [164.0, 228.0], [5.0, 95.6], [45.0, 12.21], [1.0, 7.5], [40.0, 68.21], [6391.0, 3.99], [0.0, 0.0], [5157.0, 28.45], [8700.0, 64.25], [88584.0, 8.1], [1924.0, 66.4], [4632.0, 96.54], [0.0, 0.0], [14531.0, 152.8], [4554.0, 89.79], [2188.0, 76.93], [412.0, 81.0], [12638.0, 101.75], [189.0, 84.5], [669.0, 94.0], [36726.0, 103.0], [177.0, 89.1], [4779.0, 89.2], [2738.0, 88.55], [2315.0, 89.31], [6123.0, 88.83], [2350.0, 88.66], [9724.0, 88.3], [3488.0, 88.24], [2911.0, 85.05], [639.0, 92.0], [468.0, 101.0], [2211.0, 101.5], [22959.0, 97.06], [12195.0, 95.8], [167209.0, 102.4], [32320.0, 85.6], [16616.0, 107.35], [37813.0, 87.75], [141579.0

In [34]:
base_cotacoes = np.array(lista_cotacao)

treino

In [35]:
scaler_base = StandardScaler()
base_cotacoes = scaler_base.fit_transform(base_cotacoes)
base_cotacoes

array([[-3.24948898e-01, -7.76805381e-01],
       [-3.58493191e-01, -6.60714036e-01],
       [-3.38772993e-01, -7.42913790e-01],
       [-3.58184780e-01,  6.86794037e+00],
       [-3.58438766e-01, -7.42492253e-01],
       [-3.58456908e-01, -1.99774910e-02],
       [-3.54882962e-01,  5.87036078e-01],
       [-3.57749375e-01, -1.29324241e-01],
       [-3.22971436e-01,  1.79746835e-01],
       [-3.10580547e-01, -7.63990650e-01],
       [-3.57821943e-01, -5.07190188e-01],
       [-3.47154531e-01,  2.24514085e-01],
       [-3.58438766e-01,  5.80566662e+00],
       [-3.58456908e-01, -2.56122631e-01],
       [-3.58511333e-01, -8.04036685e-01],
       [-3.25620147e-01, -7.95690248e-01],
       [-3.52542662e-01, -7.74529081e-01],
       [-3.57422822e-01, -4.94544072e-01],
       [-3.35652594e-01, -4.07791716e-01],
       [-1.98318737e-01,  6.97754004e+00],
       [-3.54157288e-01,  7.20517013e+00],
       [-3.52488237e-01, -7.95353018e-01],
       [-3.58239205e-01, -1.04284931e-01],
       [-3.

cluster

separando o numero de segmentos

In [36]:
n_cluster = df['Setor']
n_cluster = set(n_cluster)
n_cluster = len(n_cluster)
n_cluster

10

In [37]:
k_means_cotacao = KMeans(n_clusters=6)
k_means_cotacao.fit(base_cotacoes)

KMeans(n_clusters=6)

localizando os pontos de referencia

In [38]:
centroides = k_means_cotacao.cluster_centers_
centroides

array([[ 0.60847433, -0.14600072],
       [-0.33304535,  5.85143352],
       [ 8.96013511, -0.71901263],
       [ 2.96656086, -0.419443  ],
       [-0.28127728,  0.03198925],
       [-0.25104804, -0.62161283]])

vizualizando centros em 2D matematicamente pelo reverse scaler

In [39]:
# scaler_base.inverse_transform(k_means_cotacao.cluster_centers_)

add rotulos

In [40]:
rotulos = k_means_cotacao.labels_
rotulos

array([5, 5, 5, 1, 5, 4, 4, 4, 4, 5, 5, 4, 1, 4, 5, 5, 5, 5, 5, 1, 1, 5,
       4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4, 0, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4,
       0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 0, 4, 0, 3, 4, 4,
       4, 5, 4, 4, 4, 4, 4, 5, 4, 4, 5, 4, 4, 0, 4, 1, 4, 5, 2, 0, 0, 4,
       4, 5, 4, 4, 4, 4, 4, 0, 3, 1, 4, 5, 4, 4, 0, 4, 5, 4, 4, 4, 5, 5,
       4, 0, 4, 4, 4, 0, 4, 4, 4, 2, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4,
       4, 5, 0, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 5, 4, 4, 0, 0,
       0, 4, 5, 5, 4, 5, 5, 4, 4, 4, 4, 4, 5, 0, 4, 4, 4, 5, 5, 4, 4, 4,
       0, 5, 5, 4, 4, 0, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 4, 4, 4, 4, 4, 5,
       4, 5, 5, 5, 5, 0, 0, 0, 5, 4, 5, 5, 1, 4, 4, 4, 0, 0, 4, 4, 4, 4,
       5, 4, 0, 4, 4, 4, 0, 4, 0, 4, 4, 4, 4, 4, 5, 4, 0, 4, 4, 4, 4, 4,
       0, 4, 4, 4, 0, 3, 4, 0, 4, 5, 0, 3, 0, 3, 4, 0, 4, 3, 4, 4, 4, 4,
       0, 4, 5, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3])

grafico do cluster

In [41]:
grafico_cluster = px.scatter(y=base_cotacoes[:,0], x=base_cotacoes[:,1], color=rotulos)
grafico_centroid = px.scatter(y=centroides[:,0], x=centroides[:,1], size=[1,2,3,4,5,6])
grafico_geral = go.Figure(data=grafico_cluster.data + grafico_centroid.data)
grafico_geral.show()

In [42]:
n_cluster = df['Setor']
n_cluster = set(n_cluster)
nome_cluster = n_cluster
for id, x in enumerate(nome_cluster):
    id_n = id+1
    print(id_n,x)

1 Outros
2 Hospital
3 nan
4 Títulos e Val. Mob.
5 Logística
6 Shoppings
7 Hotel
8 Híbrido
9 Lajes Corporativas
10 Residencial


o Y referece ao numero de ações em circulação
o X referece ao valor da ação

logo quanto mais a direita mais cara é a ação e quanto mais alta mais fácil a liquidez da ação.

In [43]:
nome_rotulo = df['Codigo_do_fundo']
len(nome_rotulo)

306

In [45]:
grafico_c_rt = px.scatter(y=lista_lq, x=lista_vc, color=nome_rotulo)
grafico_c_rt.show()

ValueError: All arguments should have the same length. The length of argument `color` is 306, whereas the length of  previously-processed arguments ['x', 'y'] is 300

In [ ]:
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

gerando as linhas de hieraquia

In [ ]:
dendograma = dendrogram(linkage(base_cotacoes, method='ward'))
plt.title('Dendograma')
plt.xlabel('ações')
plt.ylabel('distancia')
plt.show()

com sklearn

In [ ]:
from sklearn.cluster import AgglomerativeClustering

In [ ]:
hc_cotas = AgglomerativeClustering(n_clusters=4, linkage='ward', affinity='euclidean')
rotulos = hc_cotas.fit_predict(base_cotacoes)

In [ ]:
rotulos

In [ ]:
grafico_cluster = px.scatter(y=base_cotacoes[:,0], x=base_cotacoes[:,1], color=rotulos)
grafico_cluster.show()

In [ ]:
grafico_c_rt = px.scatter(y=lista_lq, x=lista_vc, labels=nome_rotulo)
grafico_c_rt.show()

################### preço cota com rendimento ##################

pegando as colunas do dataset

In [ ]:
valor_cota = df['Preco_Atual']
rendimento_cota = df['Dividendo']

criando os eixos x e y

In [ ]:
lista_rend = [] #liquidez_diaria
lista_vc = [] #preço atual
for rd, vc in zip(rendimento_cota,valor_cota):
    try:
        vc = vc.split(' ')[-1]
        vc = vc.replace(',', '.')
        vc = float(vc)
        rd = rd.split(' ')[-1]
        rd = rd.replace(',', '.')
        rd = float(rd)
        lista_rend.append(rd)
        lista_vc.append(vc)
    except:
        pass

juntando as informações em coordenadas

In [ ]:
lista_cotacao = []
for x,y in zip(lista_rend, lista_vc):
    item = [x,y]
    lista_cotacao.append(item)

print(lista_cotacao)

In [ ]:
base_cotacoes = np.array(lista_cotacao)
scaler_base = StandardScaler()
base_cotacoes_rend = scaler_base.fit_transform(base_cotacoes)
base_cotacoes_rend

lembrando que já temos o setor

In [ ]:
k_means_cotacao = KMeans(n_clusters=6)
k_means_cotacao.fit(base_cotacoes_rend)

In [ ]:
centroides = k_means_cotacao.cluster_centers_
centroides

In [ ]:
rotulos = k_means_cotacao.labels_
rotulos

In [ ]:
n_cluster = df['Setor']
n_cluster = set(n_cluster)
nome_cluster = n_cluster
for id, x in enumerate(nome_cluster):
    id_n = id+1
    print(id_n,x)

grafico por dividendos x valor da cota

## y = referece ao rendimento mensal, quanto maior e mais alta melhor
## x = referece ao valor da cota quanto mais a direita mais cara é

In [ ]:
nome_rotulo = df['Codigo_do_fundo']
grafico_c_rt = px.scatter(y=lista_rend, x=lista_vc)
grafico_c_rt.show()

In [ ]:
grafico_cluster = px.scatter(y=base_cotacoes_rend[:,0], x=base_cotacoes_rend[:,1], color=rotulos)
grafico_centroid = px.scatter(y=centroides[:,0], x=centroides[:,1], size=[2,3,4,5,6,7])
grafico_geral = go.Figure(data=grafico_cluster.data + grafico_centroid.data)
grafico_geral.show()

In [ ]:
dendograma_rendimento = dendrogram(linkage(base_cotacoes_rend, method='ward'))

se imaginarmo uma linha entre 10 e 15 temos ali 3 linhas verticais

In [ ]:
hc_rendimento = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='ward')
rotulo_hc = hc_rendimento.fit_predict(base_cotacoes_rend)

In [ ]:
rotulo_hc

In [ ]:
grafico_cluster_rend = px.scatter(y=base_cotacoes_rend[:,0], x=base_cotacoes_rend[:,1], color=rotulo_hc)
grafico_cluster_rend.show()

vizualizando o csv que atende os requisitos

In [ ]:
dataframe = df
dataframe

In [ ]:
n_cluster = df['Setor']
n_cluster = set(n_cluster)
nome_cluster = n_cluster
for id, x in enumerate(nome_cluster):
    print(x)

In [ ]:
restricao_setor = 'Shoppings'
restricao_lq_diaria = 25000
filtro_df = dataframe[(dataframe.Preco_Atual <= 150) & (dataframe.Preco_Atual >= 7) & (dataframe.DividendYield >= 1)]
# filtro_df = dataframe[(dataframe.Codigo_do_fundo == 'MXRF11')]
filtro_df